import "./_group.css";
import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Database, Download, FileText, Filter, ImageIcon, Library, MoreHorizontal, Pencil, Plus, Search, Upload } from "lucide-react";

type Book = { id: number; title: string; author: string; year: number; category: string; isbn: string; status: string; cover?: string; tags: string[] };
const books: Book[] = [
  { id: 1, title: "Clean Code", author: "Robert C. Martin", year: 2008, category: "Technology", isbn: "9780132350884", status: "AVAILABLE", tags: ["Software", "Engineering"] },
  { id: 2, title: "The Design of Everyday Things", author: "Don Norman", year: 2013, category: "Design", isbn: "9780465050659", status: "CHECKED_OUT", tags: ["UX"] },
  { id: 3, title: "Thinking, Fast and Slow", author: "Daniel Kahneman", year: 2011, category: "Psychology", isbn: "9780374533557", status: "AVAILABLE", tags: ["Behavior"] },
  { id: 4, title: "The Pragmatic Programmer", author: "David Thomas", year: 2019, category: "Technology", isbn: "9780135957059", status: "MAINTENANCE", tags: ["Programming"] },
  { id: 5, title: "A Brief History of Time", author: "Stephen Hawking", year: 1988, category: "Science", isbn: "9780553380163", status: "LOST", tags: ["Physics"] },
];
const statusClasses: Record<string, string> = {
  AVAILABLE: "bg-green-100 text-green-800 hover:bg-green-100",
  CHECKED_OUT: "bg-blue-100 text-blue-800 hover:bg-blue-100",
  LOST: "bg-red-100 text-red-800 hover:bg-red-100",
  MAINTENANCE: "bg-orange-100 text-orange-800 hover:bg-orange-100",
};

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-background flex">
    <aside className="hidden md:flex w-64 shrink-0 flex-col bg-[hsl(var(--sidebar))] text-[hsl(var(--sidebar-foreground))]">
      <div className="h-16 flex items-center gap-3 px-6 border-b border-white/10"><div className="h-8 w-8 rounded bg-primary flex items-center justify-center font-bold">S</div><span className="font-semibold tracking-tight">SC24Lib</span></div>
      <nav className="p-4 space-y-1 text-sm"><div className="rounded-md bg-[hsl(var(--sidebar-accent))] px-3 py-2 flex items-center gap-3"><Library className="h-4 w-4" />Catalog</div><div className="px-3 py-2 text-white/60">Circulation</div><div className="px-3 py-2 text-white/60">Patrons</div><div className="px-3 py-2 text-white/60">Reports</div></nav>
    </aside>
    <div className="flex-1 flex flex-col min-w-0"><header className="h-16 bg-card border-b flex items-center justify-between px-6"><span className="text-sm text-muted-foreground">Library Management / <span className="text-foreground">Catalog</span></span><div className="flex items-center gap-3"><span className="text-sm font-medium">Alex Morgan</span><div className="h-8 w-8 rounded-full bg-primary/10 text-primary flex items-center justify-center text-xs font-semibold">AM</div></div></header><main className="flex-1 p-6 overflow-auto bg-muted/20">{children}</main></div>
  </div>;
}

function MarcPanel({ book }: { book?: Book }) {
  const fields = [["001", book?.isbn ?? "123456789"], ["003", "LIB"], ["100", `$a ${book?.author ?? "Martin, Robert C."}.`], ["245", `$a ${book?.title ?? "Clean Code"} / $c ${book?.author ?? "Robert C. Martin"}.`], ["260", "$b Prentice Hall, $c 2008."], ["650", `$a ${book?.category ?? "Software engineering"}.`]];
  return <Card><CardHeader><div className="flex justify-between"><div><CardTitle>MARC21 Editor{book ? ` — ${book.title}` : ""}</CardTitle><CardDescription>Edit bibliographic records in raw MARC format.</CardDescription></div><div className="flex gap-2"><Button variant="outline" size="sm">Validate</Button><Button size="sm">Save Record</Button></div></div></CardHeader><CardContent><Tabs defaultValue="editor"><TabsList><TabsTrigger value="editor"><FileText className="mr-2 h-4 w-4" />Field Editor</TabsTrigger><TabsTrigger value="raw">Raw MARC</TabsTrigger><TabsTrigger value="xml">MARCXML</TabsTrigger></TabsList><TabsContent value="editor"><div className="border rounded-md mt-4"><Table><TableHeader><TableRow><TableHead>Tag</TableHead><TableHead>Ind1</TableHead><TableHead>Ind2</TableHead><TableHead>Content (Subfields)</TableHead></TableRow></TableHeader><TableBody>{fields.map(([tag, content]) => <TableRow key={tag}><TableCell className="font-mono">{tag}</TableCell><TableCell> </TableCell><TableCell> </TableCell><TableCell className="font-mono text-blue-700">{content}</TableCell></TableRow>)}</TableBody></Table></div><Button variant="outline" className="w-full mt-4 border-dashed"><Plus className="mr-2 h-4 w-4" />Add Field</Button></TabsContent><TabsContent value="raw"><pre className="mt-4 p-4 bg-muted rounded-md text-sm whitespace-pre-wrap">LDR  01234nam a2200345 i 4500{"\n"}{fields.map(f => f.join("  ")).join("\n")}</pre></TabsContent><TabsContent value="xml"><pre className="mt-4 p-4 bg-muted rounded-md text-xs whitespace-pre-wrap">&lt;record xmlns="http://www.loc.gov/MARC21/slim"&gt;{"\n"}  &lt;datafield tag="245"&gt;...&lt;/datafield&gt;{"\n"}&lt;/record&gt;</pre></TabsContent></Tabs></CardContent></Card>;
}

function RemoteSearch() {
  const [searched, setSearched] = useState(false);
  return <div className="space-y-6"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="h-5 w-5 text-primary" />Z39.50 Remote Search</CardTitle><CardDescription>Query external library catalogs to import MARC records directly.</CardDescription></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-[200px_1fr_auto]"><select className="h-9 rounded-md border bg-background px-3 text-sm"><option>Library of Congress</option><option>Oxford University</option><option>British Library</option></select><div className="relative"><Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search by ISBN, Title, or Author..." /></div><Button onClick={() => setSearched(true)}>Search</Button></div></CardContent></Card>{searched && <Card><CardHeader><CardTitle className="text-base">Search Results</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Source</TableHead><TableHead>Title & Author</TableHead><TableHead>ISBN</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell><Badge variant="outline">Library of Congress</Badge></TableCell><TableCell><b>The Design of Everyday Things</b><div className="text-xs text-muted-foreground">Norman, Donald A.</div></TableCell><TableCell className="font-mono text-xs">978-0465050659</TableCell><TableCell className="text-right"><Button size="sm" variant="secondary"><Download className="mr-2 h-4 w-4" />Import</Button></TableCell></TableRow></TableBody></Table></CardContent></Card>}</div>;
}

export function Current() {
  const [tab, setTab] = useState("browse");
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All");
  const [marcBook, setMarcBook] = useState<Book>();
  const visible = useMemo(() => books.filter(b => (filter === "All" || b.status.replace("_", " ") === filter) && `${b.title} ${b.author} ${b.isbn}`.toLowerCase().includes(query.toLowerCase())), [query, filter]);
  return <Shell><div className="max-w-7xl w-full space-y-6"><div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Catalog</h1><p className="text-muted-foreground mt-1">Manage books, journals, and media resources.</p></div><div className="flex gap-2"><Button variant="outline" size="sm"><Download className="mr-2 h-4 w-4" />Export</Button><Button variant="outline" size="sm"><Upload className="mr-2 h-4 w-4" />Bulk Upload</Button><Button size="sm"><Plus className="mr-2 h-4 w-4" />Add Resource</Button></div></div>
    <Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="browse">Browse Collection</TabsTrigger><TabsTrigger value="marc" className="gap-2"><FileText className="h-4 w-4" />MARC Editor</TabsTrigger><TabsTrigger value="z3950" className="gap-2"><Database className="h-4 w-4" />Z39.50 Search</TabsTrigger></TabsList>
      <TabsContent value="browse" className="mt-6"><div className="bg-card rounded-lg border shadow-sm"><div className="p-4 border-b flex flex-col sm:flex-row gap-4 justify-between items-center"><div className="relative w-full sm:w-72"><Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search by title, author, or ISBN..." value={query} onChange={e => setQuery(e.target.value)} /></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm"><Filter className="mr-2 h-4 w-4" />Filter: {filter}</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>Filter by Status</DropdownMenuLabel><DropdownMenuSeparator />{["All", "AVAILABLE", "CHECKED OUT", "LOST", "MAINTENANCE"].map(s => <DropdownMenuItem key={s} onClick={() => setFilter(s === "AVAILABLE" ? "AVAILABLE" : s)}>{s.replace("_", " ")}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div>
        <Table><TableHeader><TableRow><TableHead className="w-[80px]">Cover</TableHead><TableHead>Title & Author</TableHead><TableHead>Category</TableHead><TableHead className="hidden md:table-cell">ISBN</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map(book => <TableRow key={book.id}><TableCell>{book.cover ? <img src={book.cover} className="h-12 w-8 object-cover rounded border" alt="" /> : <div className="h-12 w-8 bg-muted rounded border flex items-center justify-center"><ImageIcon className="h-4 w-4 text-muted-foreground" /></div>}</TableCell><TableCell><button onClick={() => { setMarcBook(book); setTab("marc"); }} className="font-medium text-left hover:text-primary hover:underline">{book.title}</button><div className="text-xs text-muted-foreground">{book.author} • {book.year}</div><div className="flex gap-1 mt-1">{book.tags.map(t => <Badge key={t} variant="secondary" className="text-[10px] font-normal px-1.5 py-0 h-4">{t}</Badge>)}</div></TableCell><TableCell><Badge variant="outline" className="font-normal">{book.category}</Badge></TableCell><TableCell className="hidden md:table-cell font-mono text-xs text-muted-foreground">{book.isbn}</TableCell><TableCell><Badge className={`${statusClasses[book.status]} border-none`}>{book.status.replace("_", " ")}</Badge></TableCell><TableCell className="text-right"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>Actions</DropdownMenuLabel><DropdownMenuItem><Pencil className="mr-2 h-4 w-4" />Edit Details</DropdownMenuItem><DropdownMenuItem onClick={() => { setMarcBook(book); setTab("marc"); }}>View MARC Record</DropdownMenuItem><DropdownMenuItem>View History</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem className="text-red-600">Delete Record</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}{visible.length === 0 && <TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">No results found.</TableCell></TableRow>}</TableBody></Table><div className="p-4 border-t flex justify-between text-xs text-muted-foreground"><span>Showing {visible.length} of {books.length} entries</span><div className="flex gap-1"><Button variant="outline" size="sm" disabled>Previous</Button><Button variant="outline" size="sm" disabled>Next</Button></div></div></div></TabsContent>
      <TabsContent value="marc" className="mt-6"><MarcPanel book={marcBook} /></TabsContent><TabsContent value="z3950" className="mt-6"><RemoteSearch /></TabsContent>
    </Tabs></div></Shell>;
}